"""
PATCH Agent — Remediation and DataHub Write-back
Auto-patches safe assets and writes incident report back to DataHub.
"""

import os
from typing import Any
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")


def generate_patch(asset: dict[str, Any], changed_field: str, new_field: str) -> str:
    """Use Groq to generate a corrected SQL patch for a broken asset."""
    client = Groq(api_key=GROQ_API_KEY)

    prompt = f"""You are a senior data engineer fixing a broken downstream asset.
A column was renamed from '{changed_field}' to '{new_field}' in the source table.

Asset name: {asset['name']}
Platform: {asset['platform']}
Domain: {asset['domain']}
Tags: {', '.join(asset['tags'])}

Write a short SQL patch (SELECT statement) that uses the new column name '{new_field}'.
Return only the SQL, nothing else. Keep it under 5 lines.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=150,
    )

    return response.choices[0].message.content.strip()


def run_patch(
    valuation_report: dict[str, Any],
    changed_field: str = "order_date",
    new_field: str = "created_at",
) -> dict[str, Any]:
    """
    Takes VALUATION output, generates patches for safe assets,
    flags critical assets for human review, and writes back to DataHub.
    """
    print(f"\n[PATCH] Processing {valuation_report['total_affected']} assets...")
    print(f"[PATCH] Column change: {changed_field} → {new_field}")

    auto_patched = []
    needs_review = []

    for asset in valuation_report["valued_assets"]:
        if asset["requires_human_review"]:
            needs_review.append(asset)
            print(f"  ⚠️  {asset['name']} → flagged for human review [REGULATORY]")
        else:
            patch_sql = generate_patch(asset, changed_field, new_field)
            auto_patched.append({
                **asset,
                "patch_sql": patch_sql,
                "patch_status": "AUTO_PATCHED",
            })
            print(f"  ✅ {asset['name']} → auto-patched")
            print(f"     SQL: {patch_sql[:80]}...")

    # Build the full incident report
    incident_report = f"""
# CASCADE BLAST RADIUS REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

## Schema Change
Source: {valuation_report['source_urn']}
Change: `{changed_field}` → `{new_field}`

## Impact Summary
- Total assets affected:    {valuation_report['total_affected']}
- Auto-patched:             {len(auto_patched)} ✅
- Requires human review:    {len(needs_review)} ⚠️
- Overall risk:             {valuation_report['overall_risk']}
- Estimated cost if unpatched: ${valuation_report['total_estimated_cost']:,}

## Executive Summary
{valuation_report['executive_summary']}

## Assets Requiring Human Review
{chr(10).join([f"- {a['name']} [{', '.join(a['tags'])}] — ${a['estimated_cost']:,}" for a in needs_review]) or "None"}

## Auto-Patched Assets
{chr(10).join([f"- {a['name']} ✅" for a in auto_patched]) or "None"}

---
Generated by CASCADE — Blast Radius Intelligence Agent
"""

    print(f"\n[PATCH] Auto-patched: {len(auto_patched)}")
    print(f"[PATCH] Needs human review: {len(needs_review)}")
    print(f"\n[PATCH] Incident Report:\n{incident_report}")

    # TODO: Replace with real DataHub write-back when token arrives
    # graph.add_tags(urn, ["CASCADE_INCIDENT"])
    # graph.save_document(urn, incident_report)
    print("[PATCH] DataHub write-back: MOCK MODE (token pending)")

    return {
        "auto_patched": auto_patched,
        "needs_review": needs_review,
        "incident_report": incident_report,
        "total_auto_patched": len(auto_patched),
        "total_needs_review": len(needs_review),
    }


if __name__ == "__main__":
    # Test PATCH with mock VALUATION output
    mock_valuation = {
        "source_urn": "urn:li:dataset:(urn:li:dataPlatform:postgres,ecommerce.orders,PROD)",
        "total_affected": 4,
        "total_estimated_cost": 80000,
        "has_regulatory": True,
        "has_revenue_critical": True,
        "overall_risk": "CRITICAL",
        "executive_summary": "This schema change poses critical regulatory and financial risks requiring immediate attention.",
        "valued_assets": [
            {"urn": "urn:1", "name": "revenue_forecast", "platform": "snowflake", "domain": "finance", "tags": ["revenue_critical"], "estimated_cost": 18000, "risk_level": "HIGH", "requires_human_review": False},
            {"urn": "urn:2", "name": "churn_prediction", "platform": "snowflake", "domain": "ml_platform", "tags": ["revenue_critical"], "estimated_cost": 18000, "risk_level": "HIGH", "requires_human_review": False},
            {"urn": "urn:3", "name": "q2_compliance_report", "platform": "snowflake", "domain": "legal", "tags": ["regulatory"], "estimated_cost": 35000, "risk_level": "CRITICAL", "requires_human_review": True},
            {"urn": "urn:4", "name": "marketing_attribution", "platform": "snowflake", "domain": "marketing", "tags": ["business_critical"], "estimated_cost": 9000, "risk_level": "MEDIUM", "requires_human_review": False},
        ],
    }

    result = run_patch(mock_valuation)
    print(f"\n[PATCH] Complete. Auto-patched: {result['total_auto_patched']}, Needs review: {result['total_needs_review']}")